// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestAPI.Models;

namespace RestAPI.Migrations
{
    [DbContext(typeof(CursusContext))]
    [Migration("20210323120749_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestAPI.Models.CursusDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cursusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("duur")
                        .HasColumnType("int");

                    b.Property<string>("titel")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("CursusDetails");
                });

            modelBuilder.Entity("RestAPI.Models.CursusInstantie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cursusDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime>("startDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("cursusDetailId");

                    b.ToTable("CursusInstanties");
                });

            modelBuilder.Entity("RestAPI.Models.CursusInstantie", b =>
                {
                    b.HasOne("RestAPI.Models.CursusDetail", "cursusDetail")
                        .WithMany("cursusInstanties")
                        .HasForeignKey("cursusDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cursusDetail");
                });

            modelBuilder.Entity("RestAPI.Models.CursusDetail", b =>
                {
                    b.Navigation("cursusInstanties");
                });
#pragma warning restore 612, 618
        }
    }
}
